### ISSUE TITLE
CVE Lookup Functionality

### ISSUE THREAD

**Issue by gavinj44** [cornerpirate/ReportCompiler#1]
Would it be possible to have the functionality to lookup any CVE's listed in the vulnerability data (description, references etc) to pull down the information relating to the issue from say cvedetails.com and tabulate the output?

**Comment by cornerpirate** [comment]
Hi Gavin,

Now that I have my life a bit more in order I am winding up to ReportCompiler being better documented. Not saying I will add everything people ask for. There is a source repo too you know :D?

But... As of today if you update to the version in this distro repo you will have a functional CVE database search. To do this right click on one or more vulnerabilities in the vuln tree and select "Lookup CVE(s)". 

This will:

1) Prompt for a filename.
2) Sanity check you when trying to overwrite a file.
3) Lookup a local CSV file for each CVE in your selected nodes' references.
4) Make a new file for you.
5) Fork a new OS process opening it with the default app for CSV file (on windows most likely excel).

That should adequately handle your request.

=== Extra Discussion for the design choices if you care ===

This does not use cvedetails.com or any other online source. I was uncomfortable scrapping given how long it might be between updates to RC. I have made the choice to support a local CSV file containing all the CVE details necessary; CVE-ID, Risk Score, Summary.

There is a repo for that which includes a python script for making your own up-to-date csv file.

https://github.com/cornerpirate/cve-offline

I will aim to update the one in the repo once a month and then add it to the current release of ReportCompiler. If I fall short in that endeavour then you can make your own by downloading all of the NIST 2.0 XML files. Then running they python script against each piped into one file.

Then simply overwrite the copy in the ReportCompiler/CVES folder.

Hope that helps
