### ISSUE TITLE
Host View is not working

### ISSUE THREAD

**Issue by s4n7h0** [cornerpirate/ReportCompiler#2]
Please check the host view option. It seems not working.

**Comment by ZephrFish** [comment]
[what do you desire?](https://www.youtube.com/watch?v=agbsQbMi7x0)

**Comment by cornerpirate** [comment]
Hi s4n7ho,

I am amazed when people I don't know use this thing. It is not broken, it has not been coded at all. I know exactly what I want from the hosts view if I ever get around to it. It simply isn't a core feature but it is 100% pretty much the next bit.

So amazed that anyone uses this hunk of crap. Especially given there is absolutely no documentation.

What do you use it for if you don't mind me asking?

**Comment by s4n7h0** [comment]
Hi @cornerpirate, this is indeed pretty cool work. I used it while documenting a VA report from a huge nessus scan. And yes !! it certainly saved my time as I didn't had a nessus running on my system to explore the scan results. I suggest you could surely maintain this good work and keep enhancing it.

**Comment by gavinj44** [comment]
Seconded!
